#!/bin/sh

ff $1 -o $1.cpp

g++ $1.cpp -o $1.out -fsanitize=undefined \
    -fsanitize=return \
    -fsanitize=bounds \
    -fsanitize=bounds-strict \
    -I $DUNE_SOURCEROOT/_build/default/runtime/ \
    $DUNE_SOURCEROOT/_build/default/runtime/libfun_rt.a
